version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: yii2-php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  composer:
    image: composer:latest
    container_name: yii2-composer
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["composer", "--version"]

volumes:
  mysql-data:
